export default function TermsConditionsPage() {
  return (
    <main className="mx-auto mt-6 flex max-w-[800px] flex-col items-center px-6">
      <div className="mb-4 rounded bg-indigo-200 px-6 py-2">
        <h1 className="text-2xl font-semibold">Terms & Conditions Page</h1>
      </div>
      <p>
        Welcome to the legal corner of the CyberBite universe, where we deal with more earthly
        matters. Don&apos;t worry, we&apos;ll try to make this as painless as possible - no alien
        abductions or wormhole shenanigans here, promise!
      </p>
      <ol className="list-decimal pl-10">
        <li>
          <p className="mt-2">
            <b>Your Agreement With Us:</b> By using our services, you&apos;re signing a cosmic
            contract with CyberBite. You don&apos;t need an advanced degree in Astro-law, simply
            agreeing to our terms and conditions will suffice. We promise not to sneak in any
            clauses about naming your first-born after our favorite galaxy.
          </p>
        </li>
        <li>
          <p>
            ``
            <b>Age Requirement:</b> You must be of legal age or have a guardian to use our service.
            We hate to break it to you, but if you&apos;re from a species that ages in reverse
            (&agrave; la Benjamin Button), we still go by Earth years.
          </p>
        </li>
        <li>
          <p>
            <b>Data Privacy:</b> We respect your privacy more than Area 51 respects its secrets.
            Your data is stored in a secure database, safe from prying alien eyes. We promise never
            to sell your information, unless it&apos;s for a lifetime supply of zero-gravity donuts.
          </p>
        </li>
        <li>
          <p>
            <b>Content:</b> All of the content on our website is owned by CyberBite or generated by
            AI, including text, graphics, logos, and images. Please don&apos;t steal them, it&apos;s
            not cool - even in a galaxy far, far away.
          </p>
        </li>
        <li>
          <p>
            <b>Delivery:</b> We aim to deliver in record time - faster than you can say
            &apos;supercalifragilisticexpialidocious&apos; backwards. But keep in mind, even our
            UFOs have their off days. If a delivery is late, remember, it&apos;s better late than
            abducted.
          </p>
        </li>
        <li>
          <p>
            <b>Payment:</b> We accept all major credit cards, cryptocurrencies, and interstellar
            credits (okay, maybe not the last one). Be sure to provide accurate payment info, or our
            financial droids may get fussy.
          </p>
        </li>
        <li>
          <p>
            <b>Amendments:</b> We may revise these terms at any time by updating this posting. So,
            keep your eyes peeled - but no need for binoculars or a telescope.
          </p>
        </li>
        <li>
          <p>
            <b>Termination:</b> In the unfortunate event you decide to stop using our service, we
            promise not to send a search party or a revengeful robot after you. But remember, once
            you leave, you&apos;ll miss out on the gastronomic galaxy tour!
          </p>
        </li>
      </ol>

      <p className="mb-3 mt-2">
        Remember, these terms aren&apos;t just here for a laugh - they&apos;re binding, so be sure
        to read and understand them fully. Now that we&apos;ve taken care of the formalities,
        let&apos;s get you back to exploring the tasty cosmos of CyberBite!
      </p>
      <div className="rounded bg-indigo-200 p-4">
        <p>
          <b>Did you actually read this?</b>; If so, I&apos;m impressed! This is a school project,
          and this page wasn&apos;t required. I just thought it would be fun to add. If you&apos;re
          still somehow reading this, I hope you have a great day! :)
        </p>
      </div>
    </main>
  )
}
